<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Owner extends \App\Entity\Owner implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'phone', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'fax', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'siret_number', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'toque_number', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'folders', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'City', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'zipCode'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'phone', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'fax', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'siret_number', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'toque_number', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'folders', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'City', '' . "\0" . 'App\\Entity\\Owner' . "\0" . 'zipCode'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Owner $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname(string $firstname): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname(string $lastname): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone(string $phone): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax(string $fax): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiretNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiretNumber', []);

        return parent::getSiretNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiretNumber(string $siret_number): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiretNumber', [$siret_number]);

        return parent::setSiretNumber($siret_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress(string $adress): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function getToqueNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToqueNumber', []);

        return parent::getToqueNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setToqueNumber(string $toque_number): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToqueNumber', [$toque_number]);

        return parent::setToqueNumber($toque_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo(?string $logo): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFolders(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolders', []);

        return parent::getFolders();
    }

    /**
     * {@inheritDoc}
     */
    public function addFolder(\App\Entity\Folder $folder): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFolder', [$folder]);

        return parent::addFolder($folder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFolder(\App\Entity\Folder $folder): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFolder', [$folder]);

        return parent::removeFolder($folder);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(string $City): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$City]);

        return parent::setCity($City);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode(int $zipCode): \App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zipCode]);

        return parent::setZipCode($zipCode);
    }

}
