<?php

namespace ContainerUoI7nl4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InvoiceController' shared autowired service.
     *
     * @return \App\Controller\InvoiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InvoiceController.php';

        $container->services['App\\Controller\\InvoiceController'] = $instance = new \App\Controller\InvoiceController(($container->privates['App\\Repository\\AboutRepository'] ?? $container->load('getAboutRepositoryService')), ($container->privates['App\\Repository\\CustomerRepository'] ?? $container->load('getCustomerRepositoryService')), ($container->privates['App\\Repository\\DiligenceRepository'] ?? $container->load('getDiligenceRepositoryService')), ($container->privates['App\\Repository\\FolderRepository'] ?? $container->load('getFolderRepositoryService')), ($container->privates['App\\Repository\\OwnerRepository'] ?? $container->load('getOwnerRepositoryService')), ($container->privates['App\\Repository\\PaymentTermsRepository'] ?? $container->load('getPaymentTermsRepositoryService')), ($container->privates['App\\Repository\\PresetDiligenceRepository'] ?? $container->load('getPresetDiligenceRepositoryService')), ($container->privates['App\\Repository\\RateRepository'] ?? $container->load('getRateRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\InvoiceController', $container));

        return $instance;
    }
}
