<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoI7nl4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoI7nl4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoI7nl4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoI7nl4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUoI7nl4\App_KernelDevDebugContainer([
    'container.build_hash' => 'UoI7nl4',
    'container.build_id' => '1eeef51c',
    'container.build_time' => 1639998211,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoI7nl4');
